INSERT INTO product_categories (name, description, department) VALUES ('Arts and Crafts', '', '');
INSERT INTO product_categories (name, description, department) VALUES ('Relationships', '', '');
INSERT INTO product_categories (name, description, department) VALUES ('Self Development', '', '');
INSERT INTO product_categories (name, description, department) VALUES ('Nutrition', '', '');
INSERT INTO product_categories (name, description, department) VALUES ('Survival', '', '');
INSERT INTO product_categories (name, description, department) VALUES ('Spirituality', '', '');

INSERT INTO supplier (name, description) VALUES ('FattyCow Book Publishing', '');
INSERT INTO supplier (name, description) VALUES ('Food for thought Publishing', '');
INSERT INTO supplier (name, description) VALUES ('Publicious Book Publishing', '');


INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('Toilet Paper Origami', 'Delight Your Guests with Fancy Folds and Simple Surface Embellishments.', 12.9, 'EUR', 'origami' , 1, 3);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('Knitting with Dog Fur', 'Better a Sweater from a Dog You Know and Love Than from a Sheep You will Never Meet' , 14.9, 'EUR', 'dog-fur', 1, 3);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('Castration - The Advantages and the Disadvantages', 'The simple 15-minute surgery gives a whopping thirteen and a half years of average life expectancy increase, cures prostate cancer and improves the body s immune system functioning.' , 27.9, 'EUR', 'castration', 1, 3);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('Fancy Coffins to Make Yourself', 'Here is the help you need for one of life s most critical undertakings - making your own coffin. This project might truly be your life s finest accomplishment.' , 22.9, 'EUR', 'coffins', 1, 2);

INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('Everything I Know about Women I learned from My Tractor', 'This "ultimate contribution to mankind" shares Rog s creative techniques for picking up babes, first dates & more. Here he guides more innocent generations down the same road to success that he enjoys in his own relationships.' , 28.9, 'EUR', 'women-tractor', 2, 3);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('If You Want Closure in Your Relationship, Start with Your Legs', 'This unique guide will show women not only how to find true love with Mr. Right, but also how to avoid Mr. Never-Gonna-Happen, Mr. Infidelity, and a variety of other Mr. Wrongs.' , 25.9, 'EUR', 'closure', 2, 3);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('Bitch, Are You Retarded?', 'EVERY WOMAN HAS A GIRLFRIEND WHO NEEDS THIS BOOK! Carlos J. Lee has been every "bad boy" that you have ever dated. He is a former dog, liar, cheater, asshole, user, manipulator and has slept with hundreds of women. ' , 20.9, 'EUR', 'are-you', 2, 1);

INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('Still Stripping After 25 Years', 'Eleanor Burns and Quilt in a Day invite you to celebrate our Silver Anniversary with Still Stripping - After 25 Years! Eleanor reminisces as she journeys from 1978, with the publication of her first book, through her 25 years of strip quilting.' , 19.9, 'EUR', 'stripping-25-years', 3, 1);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('Anybody Can Be Cool, But Awesome Takes Practice', 'Focus on biblical truths that free people to express their true personalities. Be strong to stand up to the constant lies from Satan regarding inferiority, lack of self-acceptance and peer pressure. Become the unique and beautifully designed person God has created to reflect Jesus Christ to the world.' , 31.9, 'EUR', 'anybody-can-be-cool', 3, 2);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('How To Good-Bye Depression', 'Constricting anus 100 times and denting navel 100 times everyday is effective to good-bye depression and take back youth.' , 19.9, 'EUR', 'depression',  3, 1);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('You are Sharp Enough To Be Your Own Surgeon', 'A popular California hypnotherapist describes how you can be your own plastic surgeon for making physical changes to your body using the mind-body connection. Includes techniques for breast enlargement and reduction, waist reduction, self -esteem, eliminating limiting beliefs, weight reduction concepts, and more.' , 14.9, 'EUR', 'surgeon', 3, 3);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('How To Make Money in Your Spare Time', 'A comical look on how to earn extra cash in a "not so legitimate" way. This book takes advice from the Mafia, to politicians, giving insight to readers on how quickly money can be made in the underworld.' , 10.9, 'EUR', 'money', 3, 2);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('The Penis Name Book', 'Lucky for those looking to nail down the perfect name for their (partner s) favorite body part, there is this book. Its a long, hard process coming up with an original name for a man s member, so this book does not beat around the bush.' , 9.9, 'EUR', 'name-book', 3, 2);

INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('Eating People is Wrong', 'The funniest book you would read this year.' , 12.9, 'EUR', 'eating-wrong', 4, 1);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('How to Raise Your IQ By Eating Gifted Children', 'Raise your I.Q. with a delicious "Gifted Child Fricassee."' , 14.9, 'EUR', 'iq-children', 4, 1);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('50 Ways To Eat Cock', 'With healthy chicken recipes like Risotto Cock Balls and Cock-o s, 50 Ways to Eat Cock is a contagiously humorous chicken cookbook that takes a revealing look at the folklore, history, culinary culture and nutritional benefits of this well-endowed ingredient.' , 11.9, 'EUR', 'cock-recipes', 4, 1);

INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('How To Shit in The Woods', 'Guide to relieving yourself responsibly. a once-secretive activity examines the environmental impact of too much crap (organic and otherwise) on our ever-shrinking wild outdoors.' , 13.9, 'EUR', 'woods', 5, 2);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('What To Do When The Russians Come', 'Experiences of people during the reign of the Iron Curtain. The advice and warning of this book remain relevant today. Every member in our family has read and followed advice in this book.' , 23.9, 'EUR', 'russians', 5, 2);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('How To Defend Yourself Against Alien Abduction', 'Druffel has ascertained nine techniques that witnesses use to ward off alien entities and even break off abductions in progress.' , 10.9, 'EUR', 'aliens', 5, 3);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('Zombie Racoons & Killer Bunnies', 'Here are ingenious tales that will make readers laugh or cry. Or double-check to make sure that their windows and doors are firmly locked against the things that prowl the night.Here are ingenious tales that will make readers laugh or cry. Or double-check to make sure that their windows and doors are firmly locked against the things that prowl the night.' , 11.9, 'EUR', 'racoons-bunnies', 5, 1);

INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('The Missionary Position - Mother Theresa in Theory and Practice', 'Hitchens unmasks pseudo-miracles, questions Mother Teresa s fitness to adjudicate on matters of sex and reproduction, and reports on a version of saintly ubiquity which affords genial relations with dictators, corrupt tycoons and convicted frauds.' , 18.9, 'EUR', 'theresa', 6, 2);
INSERT INTO products (name, description, price, currency, image, product_category_id, supplier_id) VALUES ('Jesus and the G-Spot', 'To remove the nasty from sex in the lives of people who live for God. I am a God-fearin, Jesus-lovin widow basing my opinions on education and a 42 year marriage where I learned to love God and my Adam! Same sex and premarital sex is not my biz-wax...a partner is a partner.' , 20.9, 'EUR', 'jesus', 6, 3);